### ISSUE TITLE
RTSE:ネームサーバー起動ボタンを押した時に起動済みのネームサーバーが終了しない

### ISSUE THREAD

**Issue by ga-sakamoto** [n-ando/OpenRTP-aist#10]
ネームサーバー起動ボタンを押すと、起動済みのネームサーバーを削除して新たにネームサーバーが起動するはずだが、何故か起動済みのネームサーバーが終了しない。
ネームサーバー削除ボタンを押すと起動済みのネームサーバーが終了する。
またrtm-naming.batを直接実行した場合でも起動済みのネームサーバーは終了しており、ネームサーバー起動ボタンを押したときのみ動作がおかしい。

**Comment by n-ando** [comment]
Modification and improvement are confirmed, issue is closed.
